GCParameters:
  UseConcMarkSweepGC: yes
  PrintGCDetails: yes
  PrintGCTimeStamps: yes
  UseGCLogFileRotation: yes
  GCLogFileSize: 1M
  Logpath: /var/log/corfu/compactor-gc.log
  NumberOfGCLogFiles: 10

ConfigFiles:
  CompactorLogbackPath: /usr/share/corfu/conf/compactor-logback.prod.xml
  TempDir: /tmp
  ClassPath: /usr/share/corfu/lib/corfudb-tools*jar
  HeapDumpPath: /image/core/compactor_oom.hprof

CorfuPaths:
  CompactorLogfile: /var/log/corfu/corfu-compactor-audit.log
  CorfuMemLogPrefix: /dev/shm/corfu.jvm.gc.
  CorfuDiskLogDir: /var/log/corfu/jvm

MemoryOptions:
  DiskBacked: yes
  DiskPath: /config/corfu-compactor/

Security:
  Keystore: /certs/keystore.jks
  KsPassword: /password/password
  Truststore: /certs/truststore.jks
  TruststorePassword: /password/password

# The below param values will be replaced during runtime by corfu-server init script
ServerAddress:
  Hostname:
  Port: 9000
  # The below params are used only for self ip discovery
  NetworkInterface: eth0
  NetworkInterfaceVersion: IPv4
