GCParameters:
  UseConcMarkSweepGC: yes
  PrintGCDetails: yes
  PrintGCTimeStamps: yes
  PrintGCDateStamps: yes
  Logpath: /var/log/corfu/compactor-gc.log
  UseGCLogFileRotation: yes
  NumberOfGCLogFiles: 10
  GCLogFileSize: 1M

ConfigFiles:
  CompactorLogbackPath: /usr/share/corfu/conf/compactor-logback.prod.xml
  TempDir: /tmp
  ClassPath: /usr/share/corfu/lib/corfudb-tools*jar
  HeapDumpPath: /image/core/compactor_oom.hprof

CorfuPaths:
  CompactorLogfile: /var/log/corfu/corfu-compactor-audit.log
  CorfuMemLogPrefix: /dev/shm/corfu.jvm.gc.
  CorfuDiskLogDir: /var/log/corfu/jvm

Security:
  Keystore: /certs/keystore.jks
  KsPassword: /password/password
  Truststore: /certs/truststore.jks
  TruststorePassword: /password/password

