# Ref: https://docs.codecov.com/docs/codecov-yaml
coverage:
  precision: 2
  round: nearest
  range: "40...70"
  ignore:
    - "generator/src/main/java/**/*"
    - "samples/**/*"
  # Ref: https://docs.codecov.com/docs/commit-status
  status:
    patch:
      off
    project:
      default:
        target: auto
        threshold: 0.2%