#!/usr/bin/env bash

for filename in /usr/share/corfu/bin/*; do
    BASENAME=$(basename "$filename")
    if [ "$BASENAME" == "corfu_server" ]; then
        ln -s /usr/share/corfu/scripts/corfu_server.sh /usr/local/bin/$BASENAME
    else
        ln -s /usr/share/corfu/scripts/cmdlet.sh /usr/local/bin/$BASENAME
    fi
done

# enable corfu-server service at boot time
if [[ -n $(which systemctl) ]]; then
    systemctl enable corfu-server
else
    update-rc.d corfu-server defaults
fi

# enable corfu-server service at boot time
if [[ -n $(which systemctl) ]]; then
    systemctl enable corfu-nonconfig-server
else
    update-rc.d corfu-nonconfig-server defaults
fi

# create necessary directories
mkdir -p /config/corfu
mkdir -p /var/log/corfu

mkdir -p /config/corfu-nonconfig
mkdir -p /var/log/corfu-nonconfig

# if user "corfu" exists, drop root privilege
CORFU_USER=corfu
corfu_user_exist=$(id -u $CORFU_USER > /dev/null 2>&1; echo $?)
if [ "$corfu_user_exist" = 0 ]; then
    chown -R $CORFU_USER:$CORFU_USER /config/corfu
    chown -R $CORFU_USER:$CORFU_USER /usr/share/corfu
    chown -R $CORFU_USER:$CORFU_USER /var/log/corfu
    sed -i -e "s/#RUN_AS_USER=/RUN_AS_USER=$CORFU_USER/" /usr/tanuki/bin/corfu-server-wrapper

    chown -R $CORFU_USER:$CORFU_USER /config/corfu-nonconfig
    chown -R $CORFU_USER:$CORFU_USER /var/log/corfu-nonconfig
    sed -i -e "s/#RUN_AS_USER=/RUN_AS_USER=$CORFU_USER/" /usr/tanuki/bin/corfu-nonconfig-server-wrapper
fi
