#!/usr/bin/env bash

for filename in /usr/share/corfu/bin/*; do
    rm /usr/local/bin/$(basename "$filename")
done

if [[ -n $(which systemctl) ]]; then
    systemctl disable corfu-server
else
    update-rc.d corfu-server remove
fi

if [[ -n $(which systemctl) ]]; then
    systemctl disable corfu-nonconfig-server
else
    update-rc.d corfu-nonconfig-server remove
fi
