
print_container_information:
	docker run -ti --rm corfudb/corfu-server:cloud sh -c "cat /app/docker.container.info.txt" || true

inspect_container:
	docker image inspect corfudb/corfu-server:cloud || true

