#!/bin/bash
# This script will install and setup bullseye for code coverage purpose

rm -f bullseye*.tar
curl -O http://apt-cache.nsbu.eng.vmware.com/apt/crosshairs/trusty/all/BullseyeCoverage-8.9.73-Linux-x64.tar
tar xf Bullseye*.tar
cd Bullseye*
if [ ! -e install ]; then
  echo Cannot find install in current dir
  exit 1
fi
rm -rf /root/bullseye
echo \$PATH > install-path
./install --prefix /root/bullseye --key 22V1PD1CVXE420mr6t3Tryeo36wHSd0P5raY
if [ "$?" != 0 ]; then
  echo Installation failed
  exit 1
fi
cd ..
rm -rf bullseye*.tar Bullseye*
cov01 -1
