#!/usr/bin/env bash

# disable corfu-server-inmem service at boot time
if [[ -n $(which systemctl) ]]; then
    systemctl disable corfu-server-inmem
else
    update-rc.d corfu-server-inmem disable
fi
