#!/usr/bin/env bash

# disable corfu-server-inmem service at boot time
if [[ -n $(which systemctl) ]]; then
    systemctl disable corfu-server-inmem
else
    update-rc.d corfu-server-inmem disable
fi

# if user "corfu" exists, drop root privilege
CORFU_USER=corfu
corfu_user_exist=$(id -u $CORFU_USER > /dev/null 2>&1; echo $?)
if [ "$corfu_user_exist" = 0 ]; then
    sed -i -e "s/#RUN_AS_USER=/RUN_AS_USER=$CORFU_USER/" /usr/tanuki/bin/corfu-server-inmem-wrapper
fi
