package org.corfudb.infrastructure.management;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;

/**
 * Heartbeat timestamp is a tuple of the heartbeat counter and the epoch.
 * This timestamp is generated by the local node and attached to the NodeState object.
 * Created by zlokhandwala on 11/13/18.
 */
@ToString
@EqualsAndHashCode
@AllArgsConstructor
public class HeartbeatTimestamp implements Comparable<HeartbeatTimestamp> {
    final long epoch;
    final long counter;

    @Override
    public int compareTo(@NonNull HeartbeatTimestamp heartbeatTimestamp) {
        return Long.compare(epoch, heartbeatTimestamp.epoch);
    }
}
