package org.corfudb.infrastructure.management;

import com.google.common.collect.ImmutableSet;
import lombok.Builder;
import lombok.Builder.Default;
import lombok.Data;
import lombok.NonNull;
import lombok.ToString;
import org.corfudb.protocols.wireprotocol.NodeView;
import org.corfudb.util.NodeLocator;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * Poll Report generated by the detectors that poll to detect failed or healed nodes.
 * This is consumed and analyzed by the Management Server to detect changes in the cluster and
 * take appropriate action.
 * Created by zlokhandwala on 3/21/17.
 */
@Data
@ToString
@Builder
public class PollReport {

    private long pollEpoch;
    @Default
    @NonNull
    private final Set<String> failingNodes = new HashSet<>();
    @Default
    @NonNull
    private final Set<String> healingNodes = new HashSet<>();
    @Default
    @NonNull
    private final Map<String, Long> outOfPhaseEpochNodes = new HashMap<>();
    @Default
    @NonNull
    private final Map<String, NodeView> nodeViewMap = new HashMap<>();

    public ImmutableSet<NodeLocator> getHealingNodesEndpoints(){
        return NodeLocator.transformToSet(healingNodes);
    }

    public ImmutableSet<NodeLocator> getOutOfPhaseNodes(){
        return NodeLocator.transformToSet(outOfPhaseEpochNodes.keySet());
    }

    public ImmutableSet<NodeLocator> getfailingNodesEndpoints(){
        return NodeLocator.transformToSet(failingNodes);
    }
}
