/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.microsoft.corfu;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CorfuLogMark implements org.apache.thrift.TEnum {
  CONTIG(0),
  HEAD(1),
  TAIL(2);

  private final int value;

  private CorfuLogMark(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CorfuLogMark findByValue(int value) { 
    switch (value) {
      case 0:
        return CONTIG;
      case 1:
        return HEAD;
      case 2:
        return TAIL;
      default:
        return null;
    }
  }
}
