/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.microsoft.corfu;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CorfuPayloadWrap implements org.apache.thrift.TBase<CorfuPayloadWrap, CorfuPayloadWrap._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CorfuPayloadWrap");

  private static final org.apache.thrift.protocol.TField ERR_FIELD_DESC = new org.apache.thrift.protocol.TField("err", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField CTNT_FIELD_DESC = new org.apache.thrift.protocol.TField("ctnt", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CorfuPayloadWrapStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CorfuPayloadWrapTupleSchemeFactory());
  }

  /**
   * 
   * @see CorfuErrorCode
   */
  public CorfuErrorCode err; // required
  public ByteBuffer ctnt; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see CorfuErrorCode
     */
    ERR((short)1, "err"),
    CTNT((short)2, "ctnt");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ERR
          return ERR;
        case 2: // CTNT
          return CTNT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ERR, new org.apache.thrift.meta_data.FieldMetaData("err", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, CorfuErrorCode.class)));
    tmpMap.put(_Fields.CTNT, new org.apache.thrift.meta_data.FieldMetaData("ctnt", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "LogPayload")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CorfuPayloadWrap.class, metaDataMap);
  }

  public CorfuPayloadWrap() {
  }

  public CorfuPayloadWrap(
    CorfuErrorCode err,
    ByteBuffer ctnt)
  {
    this();
    this.err = err;
    this.ctnt = ctnt;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CorfuPayloadWrap(CorfuPayloadWrap other) {
    if (other.isSetErr()) {
      this.err = other.err;
    }
    if (other.isSetCtnt()) {
      this.ctnt = other.ctnt;
    }
  }

  public CorfuPayloadWrap deepCopy() {
    return new CorfuPayloadWrap(this);
  }

  @Override
  public void clear() {
    this.err = null;
    this.ctnt = null;
  }

  /**
   * 
   * @see CorfuErrorCode
   */
  public CorfuErrorCode getErr() {
    return this.err;
  }

  /**
   * 
   * @see CorfuErrorCode
   */
  public CorfuPayloadWrap setErr(CorfuErrorCode err) {
    this.err = err;
    return this;
  }

  public void unsetErr() {
    this.err = null;
  }

  /** Returns true if field err is set (has been assigned a value) and false otherwise */
  public boolean isSetErr() {
    return this.err != null;
  }

  public void setErrIsSet(boolean value) {
    if (!value) {
      this.err = null;
    }
  }

  public byte[] getCtnt() {
    setCtnt(org.apache.thrift.TBaseHelper.rightSize(ctnt));
    return ctnt == null ? null : ctnt.array();
  }

  public ByteBuffer bufferForCtnt() {
    return ctnt;
  }

  public CorfuPayloadWrap setCtnt(byte[] ctnt) {
    setCtnt(ctnt == null ? (ByteBuffer)null : ByteBuffer.wrap(ctnt));
    return this;
  }

  public CorfuPayloadWrap setCtnt(ByteBuffer ctnt) {
    this.ctnt = ctnt;
    return this;
  }

  public void unsetCtnt() {
    this.ctnt = null;
  }

  /** Returns true if field ctnt is set (has been assigned a value) and false otherwise */
  public boolean isSetCtnt() {
    return this.ctnt != null;
  }

  public void setCtntIsSet(boolean value) {
    if (!value) {
      this.ctnt = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ERR:
      if (value == null) {
        unsetErr();
      } else {
        setErr((CorfuErrorCode)value);
      }
      break;

    case CTNT:
      if (value == null) {
        unsetCtnt();
      } else {
        setCtnt((ByteBuffer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ERR:
      return getErr();

    case CTNT:
      return getCtnt();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ERR:
      return isSetErr();
    case CTNT:
      return isSetCtnt();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CorfuPayloadWrap)
      return this.equals((CorfuPayloadWrap)that);
    return false;
  }

  public boolean equals(CorfuPayloadWrap that) {
    if (that == null)
      return false;

    boolean this_present_err = true && this.isSetErr();
    boolean that_present_err = true && that.isSetErr();
    if (this_present_err || that_present_err) {
      if (!(this_present_err && that_present_err))
        return false;
      if (!this.err.equals(that.err))
        return false;
    }

    boolean this_present_ctnt = true && this.isSetCtnt();
    boolean that_present_ctnt = true && that.isSetCtnt();
    if (this_present_ctnt || that_present_ctnt) {
      if (!(this_present_ctnt && that_present_ctnt))
        return false;
      if (!this.ctnt.equals(that.ctnt))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(CorfuPayloadWrap other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    CorfuPayloadWrap typedOther = (CorfuPayloadWrap)other;

    lastComparison = Boolean.valueOf(isSetErr()).compareTo(typedOther.isSetErr());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetErr()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.err, typedOther.err);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCtnt()).compareTo(typedOther.isSetCtnt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCtnt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ctnt, typedOther.ctnt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CorfuPayloadWrap(");
    boolean first = true;

    sb.append("err:");
    if (this.err == null) {
      sb.append("null");
    } else {
      sb.append(this.err);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ctnt:");
    if (this.ctnt == null) {
      sb.append("null");
    } else {
      sb.append(this.ctnt);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CorfuPayloadWrapStandardSchemeFactory implements SchemeFactory {
    public CorfuPayloadWrapStandardScheme getScheme() {
      return new CorfuPayloadWrapStandardScheme();
    }
  }

  private static class CorfuPayloadWrapStandardScheme extends StandardScheme<CorfuPayloadWrap> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CorfuPayloadWrap struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ERR
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.err = CorfuErrorCode.findByValue(iprot.readI32());
              struct.setErrIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CTNT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ctnt = iprot.readBinary();
              struct.setCtntIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CorfuPayloadWrap struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.err != null) {
        oprot.writeFieldBegin(ERR_FIELD_DESC);
        oprot.writeI32(struct.err.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.ctnt != null) {
        oprot.writeFieldBegin(CTNT_FIELD_DESC);
        oprot.writeBinary(struct.ctnt);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CorfuPayloadWrapTupleSchemeFactory implements SchemeFactory {
    public CorfuPayloadWrapTupleScheme getScheme() {
      return new CorfuPayloadWrapTupleScheme();
    }
  }

  private static class CorfuPayloadWrapTupleScheme extends TupleScheme<CorfuPayloadWrap> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CorfuPayloadWrap struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetErr()) {
        optionals.set(0);
      }
      if (struct.isSetCtnt()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetErr()) {
        oprot.writeI32(struct.err.getValue());
      }
      if (struct.isSetCtnt()) {
        oprot.writeBinary(struct.ctnt);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CorfuPayloadWrap struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.err = CorfuErrorCode.findByValue(iprot.readI32());
        struct.setErrIsSet(true);
      }
      if (incoming.get(1)) {
        struct.ctnt = iprot.readBinary();
        struct.setCtntIsSet(true);
      }
    }
  }

}

