name: Code Coverage Reporter

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_analysis:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Prepare Corfu
        run: .ci/infrastructure-docker-build.sh docker
        shell: bash

      # "-pl coverage -am" builds coverage module and also makes its dependencies thereby running their unit tests.
      #
      # Maven test failures can be ignored with "-Dmaven.test.failure.ignore=true" because,
      # since we are running 3 suits at once in this job, it can be time-consuming to re-run them
      # for every single intermittent/flaky test failures. Moreover, all the 3 suits are ensured to be run successfully
      # (with individual retry option) in other GitHub Action files before merging the PR.
      #
      # -Dcode-coverage=true sets the activation property to activate "it" and "universe" profiles simultaneously.
      # This system property is also used for setting the OS environment variable to be used by the server
      # shell scripts in the ITs.
      # Tip: "help:active-profiles" instead of "clean verify" lists the activated profiles along with the mvn build order.
      - name: run tests
        run: ./mvnw -pl :coverage -am clean verify -Dmaven.test.failure.ignore=true -Dcode-coverage=true -Dmaven.javadoc.skip=true -Dcheckstyle.skip -T 1C

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/target/site/jacoco-aggregate/jacoco.xml

      - name: Upload Codecov report
        uses: codecov/codecov-action@v3
        with:
          files: coverage/target/site/jacoco-aggregate/jacoco.xml
