name: Injection Framework Test

on: pull_request

# Cancel Previous Runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  injection_framework_test:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    env:
      PKG_USERNAME: ${{ secrets.pkg_username }}
      PUBLISH_TOKEN: ${{ secrets.publish_token }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
          check-latest: true
          cache-dependency-path: '**/pom.xml'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Docker
        run: |
          for pkg in docker.io docker-ce docker-ce-cli docker-ce-rootless-extras docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh ./get-docker.sh --version 24.0.9
          /usr/bin/docker version
          /usr/bin/docker info

      - name: Prepare top of trunk docker image
        run: |
          .ci/infrastructure-docker-build.sh docker
          .ci/generator-docker-build.sh
        shell: bash

      - name: Set corfu server version env variable
        run: echo "CORFU_SERVER_VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          repository: 'CorfuDB/corfudb-cloud'
          ref: master

      - name: Build universe-core
        working-directory: ./universe
        run: rm -rf ~/.m2/repository/org/corfudb && ./gradlew clean publishToMavenLocal

      - name: Set corfu server version
        working-directory: ./tests
        run: ./gradlew setCorfuServerVersion -Pcorfu.server.version=${{ env.CORFU_SERVER_VERSION }}

      - name: Run injection framework with universe framework
        working-directory: ./tests
        run: ./gradlew clean test -Dtags=longevity-docker

      - name: upload longevity logs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: injection-framework-logs
          retention-days: 3
          path: ./tests/build/corfu-longevity-app/correctness.log

      - name: Run injection framework verification
        working-directory: ./tests/build/corfu-longevity-app
        run: docker run -v ${PWD}/correctness.log:/injection_framework/correctness.log corfudb/injection-framework-verification:latest
